# -*- coding: utf-8 -*-
import os, sys

if sys.version_info < (3, 0):
    reload(sys)
    sys.setdefaultencoding('utf-8')

BASE = os.path.dirname(os.path.abspath(__file__))
EM = "\u2014"

def w(path, txt):
    with open(path, "w", encoding="utf-8") as f:
        f.write(txt)
    print("  [OK] " + os.path.basename(path))

def main():
    print()
    print("  GuruDev Deploy v23b")
    print("  Hubstry-DeepTech")
    print()

    # === README.md ===
    w(os.path.join(BASE, "README.md"),
    "# GuruDev Core \u00b7 Hubstry-DeepTech\n"
    "\n"
    "> **Idioma**: **Portugu\u00eas** | [English](README_EN.md)\n"
    "\n"
    "**GuruDev** \u00e9 uma linguagem de programa\u00e7\u00e3o hol\u00edstica e ontol\u00f3gica, criada integralmente por **Guilherme Gon\u00e7alves Machado** " + EM + " desde a concep\u00e7\u00e3o te\u00f3rica at\u00e9 a arquitetura completa, incluindo a inven\u00e7\u00e3o da **GuruMatrix** (\u00e1lgebra hexarrelacional \u03c0\u221af(A)) e toda a fundamenta\u00e7\u00e3o ontol\u00f3gica que diferencia a linguagem. Desenvolvida sob o guarda-chuva da deep tech **Hubstry-DeepTech**, GuruDev n\u00e3o \u00e9 um \"port\" ou wrapper de nenhuma linguagem existente " + EM + " \u00e9 uma cria\u00e7\u00e3o original, constru\u00edda do zero.\n"
    "\n"
    "---\n"
    "\n"
    "## Vis\u00e3o\n"
    "\n"
    "GuruDev integra lingu\u00edstica, intelig\u00eancia artificial, epistemologia e engenharia de software para criar um paradigma de programa\u00e7\u00e3o **multimodal e sem\u00e2ntico**, alinhado \u00e0s demandas da pr\u00f3xima gera\u00e7\u00e3o de sistemas computacionais. Sua sintaxe \u00fanica de blocos ontol\u00f3gicos, anota\u00e7\u00f5es sem\u00e2nticas e interoperabilidade multil\u00edngue a diferencia de qualquer outra linguagem de programa\u00e7\u00e3o existente.\n"
    "\n"
    "A ideia central \u00e9 usar GuruDev com IA para que a m\u00e1quina capture n\u00edvel sem\u00e2ntico " + EM + " transcendendo a execu\u00e7\u00e3o puramente sint\u00e1tica e alcan\u00e7ando compreens\u00e3o ontol\u00f3gica do c\u00f3digo.\n"
    "\n"
    "---\n"
    "\n"
    "## O Diferencial Ontol\u00f3gico\n"
    "\n"
    "GuruDev n\u00e3o \u00e9 \"Python em portugu\u00eas\". \u00c9 uma linguagem com identidade pr\u00f3pria, fundamentada em tr\u00eas pilares acad\u00eamicos publicados no Zenodo:\n"
    "\n"
    "### 1. Programa\u00e7\u00e3o Comparada " + EM + " Fundamentos Te\u00f3ricos\n"
    "A linguagem se baseia na an\u00e1lise estrutural de 15+ linguagens de programa\u00e7\u00e3o, extraindo padr\u00f5es sem\u00e2nticos universais para criar uma gram\u00e1tica que \u00e9 simultaneamente acess\u00edvel e expressiva.\n"
    "\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.20028887](https://doi.org/10.5281/zenodo.20028887)\n"
    "\n"
    "### 2. IMIP " + EM + " Interface de M\u00faltiplas Interpreta\u00e7\u00f5es Param\u00e9tricas\n"
    "O **DISPATCH_ON_HERMENEUTICS** (\u00a74.3 do IMIP) define 7 n\u00edveis de interpreta\u00e7\u00e3o para texto computacional, permitindo que a mesma express\u00e3o seja compreendida em m\u00faltiplas camadas sem\u00e2nticas. A **Conten\u00e7\u00e3o Constitucional** (\u00a75.5) restringe tokens por inst\u00e2ncia, garantindo seguran\u00e7a ontol\u00f3gica.\n"
    "\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.19772798](https://doi.org/10.5281/zenodo.19772798)\n"
    "\n"
    "### 3. \u03c0\u221af(A) " + EM + " \u00c1lgebra Hexarrelacional (GuruMatrix)\n"
    "A **GuruMatrix** \u00e9 um tensor de 5 dimens\u00f5es que rastreia opera\u00e7\u00f5es por categoria, sem\u00e2ntica e n\u00edvel de interpreta\u00e7\u00e3o " + EM + " a estrutura de dados central que d\u00e1 poder \u00e0 m\u00e1quina de capturar n\u00edvel sem\u00e2ntico. Este trabalho tamb\u00e9m explora a interse\u00e7\u00e3o com computa\u00e7\u00e3o qu\u00e2ntica.\n"
    "\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.19775021](https://doi.org/10.5281/zenodo.19775021)\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.18776401](https://doi.org/10.5281/zenodo.18776401)\n"
    "\n"
    "---\n"
    "\n"
    "## Sintaxe Ontol\u00f3gica " + EM + " O Motor\n"
    "\n"
    "A sintaxe da GuruDev permite **blocos ontol\u00f3gicos** com capacidade de subescrita, compensa\u00e7\u00e3o e interoperabilidade:\n"
    "\n"
    "| Construto | Sintaxe | Descri\u00e7\u00e3o |\n"
    "|---|---|---|\n"
    "| Bloco | `[$$bloco$$]` ... `[$$/bloco$$]` | Unidade ontol\u00f3gica principal |\n"
    "| Sobrescrita | `[$$sobrescrita$$]` ... `[$$/sobrescrita$$]` | Redefine comportamento de opera\u00e7\u00f5es |\n"
    "| C\u00f3digo GuruDev | `\u00a1codigo!` ... `!/codigo!` | C\u00f3digo nativo dentro do bloco |\n"
    "| Subescrita Python | `\u00bfpython?` ... `?/python?` | Interoperabilidade com Python (exec()) |\n"
    "| Compensa\u00e7\u00e3o | `$$compensacao$$` ... `$$/compensacao$$` | Fallback autom\u00e1tico em caso de erro |\n"
    "| Tratamento de erro | `$$erro]` | Captura falhas com AST execut\u00e1vel |\n"
    "\n"
    "---\n"
    "\n"
    "## Verticais de Neg\u00f3cio\n"
    "\n"
    "GuruDev foi projetada com foco em quatro verticais estrat\u00e9gicas:\n"
    "\n"
    "- **Seguran\u00e7a Cibern\u00e9tica** " + EM + " Blocos ontol\u00f3gicos com conten\u00e7\u00e3o constitucional proporcionam seguran\u00e7a em n\u00edvel sem\u00e2ntico, impedindo interpreta\u00e7\u00f5es n\u00e3o autorizadas de c\u00f3digo.\n"
    "- **Games** " + EM + " A multimodalidade da linguagem e a capacidade de redefinir comportamentos via sobrescrita permitem criar sistemas de regras din\u00e2micos e adapt\u00e1veis para engines de jogos.\n"
    "- **Interoperabilidade entre Linguagens** " + EM + " Subescritas permitem executar Python, JavaScript, Rust e outras linguagens dentro de blocos ontol\u00f3gicos, com rastreamento sem\u00e2ntico via GuruMatrix.\n"
    "- **IA Geral** " + EM + " A integra\u00e7\u00e3o nativa com o DISPATCH_ON_HERMENEUTICS permite que modelos de IA operem em m\u00faltiplos n\u00edveis de interpreta\u00e7\u00e3o, capturando sem\u00e2ntica e n\u00e3o apenas sintaxe.\n"
    "\n"
    "---\n"
    "\n"
    "## Estado Atual do Projeto (Maio 2026)\n"
    "\n"
    "### Funcionalidades Implementadas\n"
    "- **38/38 testes passando** " + EM + " suite completa de testes automatizados\n"
    "- **Lexer (PLY)** " + EM + " m\u00e1quina de estados com 9 estados l\u00e9xicos dedicados\n"
    "- **Parser (PLY)** " + EM + " gram\u00e1tica completa incluindo blocos ontol\u00f3gicos\n"
    "- **Interpretador** " + EM + " execu\u00e7\u00e3o completa com motor ontol\u00f3gico ativo\n"
    "- **REPL interativo** " + EM + " modo read-eval-print com auto-finaliza\u00e7\u00e3o\n"
    "- **CLI** " + EM + " `gurudev run`, `gurudev test`, `gurudev repl`\n"
    "- **M\u00e9todos String** (18) " + EM + " `tamanho()`, `maiusculo()`, `minusculo()`, `contem()`, `substituir()`, `fatiar()`, `dividir()`, `remover_espacos()`, `inverter()`, `repetir()`, `comeca_com()`, `termina_com()`, `indice_de()`, `ultima_posicao()`, `para_maiusculo()`, `para_minusculo()`, `eh_numero()`, `eh_vazio()`\n"
    "- **M\u00e9todos Array** (17) " + EM + " `adicionar()`, `remover()`, `tamanho()`, `contem()`, `indice_de()`, `ordenar()`, `inverter()`, `fatiar()`, `juntar()`, `copiar()`, `limpar()`, `primeiro()`, `ultimo()`, `mapa()`, `filtrar()`, `reduzir()`, `plano()`\n"
    "- **Classes** " + EM + " `isto`, `this`, `iniciar()`, propriedades, m\u00e9todos\n"
    "- **Motor Ontol\u00f3gico** " + EM + " blocos, subescritas, compensa\u00e7\u00e3o ativos\n"
    "\n"
    "### Instala\u00e7\u00e3o\n"
    "\n"
    "```bash\ngit clone https://github.com/Hubstry-DeepTech/gurudev-core.git\ncd gurudev-core\npython -m pip install -e .\n```\n"
    "\n"
    "### Uso\n"
    "\n"
    "```bash\n# Executar arquivo .guru\ngurudev run examples/calc.guru\n\n# Exemplo ontol\u00f3gico\ngurudev run examples/ontologico.guru\n\n# REPL interativo\ngurudev repl\n\n# Suite de testes\ngurudev test\n```\n"
    "\n"
    "---\n"
    "\n"
    "## Estrutura do Reposit\u00f3rio\n"
    "\n"
    "```\ngurudev-core/\n"
    "\u251c\u2500\u2500 src/\n"
    "\u2502   \u251c\u2500\u2500 lexer/                  # M\u00e1quina de estados PLY\n"
    "\u2502   \u251c\u2500\u2500 parser.py               # Gram\u00e1tica com blocos ontol\u00f3gicos\n"
    "\u2502   \u251c\u2500\u2500 interpreter.py          # Interpretador + motor ontol\u00f3gico\n"
    "\u2502   \u251c\u2500\u2500 ast_nodes.py            # N\u00f3s da AST\n"
    "\u2502   \u2514\u2500\u2500 repl.py                 # REPL interativo\n"
    "\u251c\u2500\u2500 examples/\n"
    "\u2502   \u251c\u2500\u2500 calc.guru               # Exemplo String/Array methods\n"
    "\u2502   \u2514\u2500\u2500 ontologico.guru         # Exemplo motor ontol\u00f3gico\n"
    "\u251c\u2500\u2500 run_interpreter_test.py     # Suite de testes (38)\n"
    "\u251c\u2500\u2500 pyproject.toml\n"
    "\u251c\u2500\u2500 README.md                   # Este arquivo (PT-BR)\n"
    "\u251c\u2500\u2500 README_EN.md                # Vers\u00e3o em ingl\u00eas\n"
    "\u2514\u2500\u2500 LICENSE                     # Business Source License 1.1\n```\n"
    "\n"
    "---\n"
    "\n"
    "## Links Oficiais\n"
    "\n"
    "- **Site Hubstry:** [www.hubstry.dev](https://www.hubstry.dev)\n"
    "- **Site GuruDev:** [gurudev-tech.site](https://gurudev-tech.site)\n"
    "- **Reposit\u00f3rio:** [github.com/Hubstry-DeepTech/gurudev-core](https://github.com/Hubstry-DeepTech/gurudev-core)\n"
    "\n"
    "---\n"
    "\n"
    "## Sobre o Criador\n"
    "\n"
    "**Guilherme Gon\u00e7alves Machado** \u00e9 o criador original da GuruDev " + EM + " desde a concep\u00e7\u00e3o da ideia, passando pela arquitetura, design da linguagem, inven\u00e7\u00e3o da GuruMatrix, e toda a fundamenta\u00e7\u00e3o te\u00f3rica publicada nos papers acad\u00eamicos. Toda a propriedade intelectual da linguagem, incluindo sua gram\u00e1tica, sintaxe ontol\u00f3gica, motor de interpreta\u00e7\u00e3o e estruturas de dados, \u00e9 cria\u00e7\u00e3o original sua.\n"
    "\n"
    "---\n"
    "\n"
    "## Licen\u00e7a\n"
    "\n"
    "Este projeto est\u00e1 licenciado sob a **Business Source License 1.1 (BSL 1.1)**.\n"
    "\n"
    "O uso **n\u00e3o comercial** (pesquisa acad\u00eamica, educa\u00e7\u00e3o, projetos pessoais) \u00e9 livre e encorajado. O uso comercial (venda, licenciamento, SaaS, integra\u00e7\u00e3o em produtos comerciais) requer autoriza\u00e7\u00e3o expressa do criador.\n"
    "\n"
    "Consulte o arquivo [LICENSE](LICENSE) para os termos completos.\n"
    "\n"
    "\u00a9 2024-2026 Guilherme Gon\u00e7alves Machado \u00b7 Hubstry-DeepTech. Todos os direitos reservados.\n"
    )

    # === README_EN.md ===
    w(os.path.join(BASE, "README_EN.md"),
    "# GuruDev Core \u00b7 Hubstry-DeepTech\n"
    "\n"
    "> **Language**: [Portugu\u00eas](README.md) | **English**\n"
    "\n"
    "**GuruDev** is a holistic and ontological programming language, entirely created by **Guilherme Gon\u00e7alves Machado** " + EM + " from theoretical conception through complete architecture, including the invention of **GuruMatrix** (hexarrelational algebra \u03c0\u221af(A)) and the entire ontological foundation that differentiates the language. Developed under the **Hubstry-DeepTech** umbrella, GuruDev is not a \"port\" or wrapper of any existing language " + EM + " it is an original creation, built from scratch.\n"
    "\n"
    "---\n"
    "\n"
    "## Vision\n"
    "\n"
    "GuruDev integrates linguistics, artificial intelligence, epistemology, and software engineering to create a **multimodal and semantic** programming paradigm aligned with the demands of next-generation computational systems. Its unique syntax of ontological blocks, semantic annotations, and multilingual interoperability differentiates it from any other programming language in existence.\n"
    "\n"
    "The core idea is to use GuruDev with AI so that machines capture semantic level " + EM + " transcending purely syntactic execution and achieving ontological comprehension of code.\n"
    "\n"
    "---\n"
    "\n"
    "## The Ontological Differentiator\n"
    "\n"
    "GuruDev is not \"Python in Portuguese.\" It is a language with its own identity, grounded in three academic pillars published on Zenodo:\n"
    "\n"
    "### 1. Comparative Programming " + EM + " Theoretical Foundations\n"
    "The language is based on the structural analysis of 15+ programming languages, extracting universal semantic patterns to create a grammar that is simultaneously accessible and expressive.\n"
    "\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.20028887](https://doi.org/10.5281/zenodo.20028887)\n"
    "\n"
    "### 2. IMIP " + EM + " Multiple Interpretive Parametric Interface\n"
    "The **DISPATCH_ON_HERMENEUTICS** (IMIP \u00a74.3) defines 7 interpretation levels for computational text, allowing the same expression to be understood across multiple semantic layers. **Constitutional Containment** (\u00a75.5) restricts tokens per instance, ensuring ontological security.\n"
    "\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.19772798](https://doi.org/10.5281/zenodo.19772798)\n"
    "\n"
    "### 3. \u03c0\u221af(A) " + EM + " Hexarrelational Algebra (GuruMatrix)\n"
    "The **GuruMatrix** is a 5-dimensional tensor that tracks operations by category, semantics, and interpretation level " + EM + " the central data structure that empowers machines to capture semantic level. This work also explores the intersection with quantum computing.\n"
    "\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.19775021](https://doi.org/10.5281/zenodo.19775021)\n"
    "\U0001f4c4 **doi:** [10.5281/zenodo.18776401](https://doi.org/10.5281/zenodo.18776401)\n"
    "\n"
    "---\n"
    "\n"
    "## Ontological Syntax " + EM + " The Engine\n"
    "\n"
    "GuruDev's syntax enables **ontological blocks** with rewriting, compensation, and interoperability capabilities:\n"
    "\n"
    "| Construct | Syntax | Description |\n"
    "|---|---|---|\n"
    "| Block | `[$$bloco$$]` ... `[$$/bloco$$]` | Main ontological unit |\n"
    "| Override | `[$$sobrescrita$$]` ... `[$$/sobrescrita$$]` | Redefines operation behavior |\n"
    "| GuruDev Code | `\u00a1codigo!` ... `!/codigo!` | Native code inside block |\n"
    "| Python Subscript | `\u00bfpython?` ... `?/python?` | Interoperability with Python (exec()) |\n"
    "| Compensation | `$$compensacao$$` ... `$$/compensacao$$` | Automatic fallback on error |\n"
    "| Error Handling | `$$erro]` | Captures failures with executable AST |\n"
    "\n"
    "---\n"
    "\n"
    "## Business Verticals\n"
    "\n"
    "GuruDev was designed with focus on four strategic verticals:\n"
    "\n"
    "- **Cybersecurity** " + EM + " Ontological blocks with constitutional containment provide security at the semantic level, preventing unauthorized code interpretations.\n"
    "- **Games** " + EM + " The language's multimodality and the ability to redefine behaviors via override enable creation of dynamic, adaptable rule systems for game engines.\n"
    "- **Cross-Language Interoperability** " + EM + " Subscripts allow executing Python, JavaScript, Rust, and other languages within ontological blocks, with semantic tracking via GuruMatrix.\n"
    "- **General AI** " + EM + " Native integration with DISPATCH_ON_HERMENEUTICS allows AI models to operate across multiple interpretation levels, capturing semantics and not just syntax.\n"
    "\n"
    "---\n"
    "\n"
    "## Current Project Status (May 2026)\n"
    "\n"
    "### Implemented Features\n"
    "- **38/38 tests passing** " + EM + " complete automated test suite\n"
    "- **Lexer (PLY)** " + EM + " state machine with 9 dedicated lexical states\n"
    "- **Parser (PLY)** " + EM + " complete grammar including ontological blocks\n"
    "- **Interpreter** " + EM + " full execution with active ontological engine\n"
    "- **Interactive REPL** " + EM + " read-eval-print with auto-finalization\n"
    "- **CLI** " + EM + " `gurudev run`, `gurudev test`, `gurudev repl`\n"
    "- **String Methods** (18) " + EM + " `tamanho()`, `maiusculo()`, `minusculo()`, `contem()`, `substituir()`, and more\n"
    "- **Array Methods** (17) " + EM + " `adicionar()`, `remover()`, `tamanho()`, `ordenar()`, `filtrar()`, and more\n"
    "- **Classes** " + EM + " `isto`, `this`, `iniciar()`, properties, methods\n"
    "- **Ontological Engine** " + EM + " blocks, subscripts, compensation active\n"
    "\n"
    "### Installation\n"
    "\n"
    "```bash\ngit clone https://github.com/Hubstry-DeepTech/gurudev-core.git\ncd gurudev-core\npython -m pip install -e .\n```\n"
    "\n"
    "### Usage\n"
    "\n"
    "```bash\n# Run a .guru file\ngurudev run examples/calc.guru\n\n# Ontological example\ngurudev run examples/ontologico.guru\n\n# Interactive REPL\ngurudev repl\n\n# Test suite\ngurudev test\n```\n"
    "\n"
    "---\n"
    "\n"
    "## Repository Structure\n"
    "\n"
    "```\ngurudev-core/\n"
    "\u251c\u2500\u2500 src/\n"
    "\u2502   \u251c\u2500\u2500 lexer/                  # PLY state machine\n"
    "\u2502   \u251c\u2500\u2500 parser.py               # Grammar with ontological blocks\n"
    "\u2502   \u251c\u2500\u2500 interpreter.py          # Tree-walking interpreter + ontological engine\n"
    "\u2502   \u251c\u2500\u2500 ast_nodes.py            # AST nodes\n"
    "\u2502   \u2514\u2500\u2500 repl.py                 # Interactive REPL\n"
    "\u251c\u2500\u2500 examples/\n"
    "\u2502   \u251c\u2500\u2500 calc.guru               # String/Array methods example\n"
    "\u2502   \u2514\u2500\u2500 ontologico.guru         # Ontological engine example\n"
    "\u251c\u2500\u2500 run_interpreter_test.py     # Test suite (38 tests)\n"
    "\u251c\u2500\u2500 pyproject.toml\n"
    "\u251c\u2500\u2500 README.md                   # Portuguese version\n"
    "\u251c\u2500\u2500 README_EN.md                # This file (English)\n"
    "\u2514\u2500\u2500 LICENSE                     # Business Source License 1.1\n```\n"
    "\n"
    "---\n"
    "\n"
    "## Official Links\n"
    "\n"
    "- **Hubstry Website:** [www.hubstry.dev](https://www.hubstry.dev)\n"
    "- **GuruDev Website:** [gurudev-tech.site](https://gurudev-tech.site)\n"
    "- **Repository:** [github.com/Hubstry-DeepTech/gurudev-core](https://github.com/Hubstry-DeepTech/gurudev-core)\n"
    "\n"
    "---\n"
    "\n"
    "## About the Creator\n"
    "\n"
    "**Guilherme Gon\u00e7alves Machado** is the original creator of GuruDev " + EM + " from the initial conception of the idea, through the architecture, language design, invention of the GuruMatrix, and the entire theoretical foundation published in academic papers. All intellectual property of the language, including its grammar, ontological syntax, interpretation engine, and data structures, is his original creation.\n"
    "\n"
    "---\n"
    "\n"
    "## License\n"
    "\n"
    "This project is licensed under the **Business Source License 1.1 (BSL 1.1)**.\n"
    "\n"
    "**Non-commercial** use (academic research, education, personal projects) is free and encouraged. **Commercial** use (selling, licensing, SaaS, integration into commercial products) requires express authorization from the creator.\n"
    "\n"
    "See the [LICENSE](LICENSE) file for full terms.\n"
    "\n"
    "\u00a9 2024-2026 Guilherme Gon\u00e7alves Machado \u00b7 Hubstry-DeepTech. All rights reserved.\n"
    )

    # === LICENSE ===
    w(os.path.join(BASE, "LICENSE"),
    "Business Source License 1.1\n"
    "\n"
    "Parameters\n"
    "\n"
    "Licensor:             Guilherme Goncalves Machado (Hubstry-DeepTech)\n"
    "\n"
    "Licensed Work:        GuruDev Core (gurudev-core)\n"
    "                      The GuruDev programming language, including its lexer,\n"
    "                      parser, interpreter, ontological engine, GuruMatrix\n"
    "                      architecture, grammar, syntax, and all associated\n"
    "                      documentation, examples, and tooling.\n"
    "\n"
    "Additional Use Grant: You may use the Licensed Work for academic research,\n"
    "                      education, personal projects, and non-commercial\n"
    "                      evaluation purposes without a separate commercial\n"
    "                      license.\n"
    "\n"
    "Change Date:          2029-05-07\n"
    "\n"
    "Change License:       GNU General Public License v3.0 (GPL-3.0)\n"
    "\n"
    "Notice\n"
    "\n"
    "The Business Source License (this document, or the \"License\") is not an Open\n"
    "Source license. However, the Licensed Work will eventually be made available\n"
    "under an Open Source License, as stated below.\n"
    "\n"
    "Licensor Copyright Notice:\n"
    "\n"
    "    Copyright (c) 2024-2026 Guilherme Goncalves Machado\n"
    "    All rights reserved.\n"
    "\n"
    "License Terms\n"
    "\n"
    "1. Grant of License\n"
    "\n"
    "   Subject to the terms and conditions of this License, Licensor hereby grants\n"
    "   to you a non-exclusive, worldwide, non-sublicensable, non-transferable,\n"
    "   limited license to use, reproduce, modify, and prepare Derivative Works of\n"
    "   the Licensed Work, solely for non-commercial purposes. Commercial use of\n"
    "   the Licensed Work, including but not limited to selling, licensing, renting,\n"
    "   leasing, or offering the Licensed Work as a service (SaaS), is expressly\n"
    "   prohibited without a separate written agreement with Licensor.\n"
    "\n"
    "   For the avoidance of doubt, \"non-commercial purposes\" includes:\n"
    "   - Academic research and publication\n"
    "   - Educational use and teaching\n"
    "   - Personal projects and experimentation\n"
    "   - Open-source contribution (non-commercial)\n"
    "   - Evaluation and testing\n"
    "\n"
    "   \"Commercial purposes\" includes, but is not limited to:\n"
    "   - Selling or licensing the Licensed Work or Derivative Works\n"
    "   - Using the Licensed Work in a commercial product or service\n"
    "   - Offering the Licensed Work as a managed service\n"
    "   - Integrating the Licensed Work into commercial software\n"
    "\n"
    "2. Restrictions\n"
    "\n"
    "   a. You may not sell, lease, or rent the Licensed Work.\n"
    "   b. You may not offer the Licensed Work as a managed service.\n"
    "   c. You may not use the Licensed Work for competitive purposes.\n"
    "   d. You may not remove or alter any proprietary notices.\n"
    "   e. You must retain all copyright, patent, trademark, and attribution\n"
    "      notices present in the Licensed Work.\n"
    "   f. You must include a copy of this License with any distribution.\n"
    "\n"
    "3. Ownership\n"
    "\n"
    "   The Licensed Work and all intellectual property rights therein are and shall\n"
    "   remain the exclusive property of Licensor. This License does not grant you\n"
    "   any ownership rights in the Licensed Work.\n"
    "\n"
    "4. Patent Grant\n"
    "\n"
    "   Subject to the terms and conditions of this License, Licensor hereby grants\n"
    "   to you a non-exclusive, worldwide, non-sublicensable, non-transferable,\n"
    "   limited license under any patent claims licensable by Licensor that are\n"
    "   necessarily infringed by the use or sale of the Licensed Work, solely for\n"
    "   non-commercial purposes.\n"
    "\n"
    "5. Limitation of Liability\n"
    "\n"
    "   IN NO EVENT SHALL LICENSOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
    "   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
    "   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;\n"
    "   OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\n"
    "   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR\n"
    "   OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE\n"
    "   LICENSED WORK, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
    "\n"
    "6. Termination\n"
    "\n"
    "   This License and the rights granted hereunder will terminate automatically\n"
    "   upon any breach by you of the terms of this License. Upon termination, you\n"
    "   must cease all use, modification, and distribution of the Licensed Work.\n"
    "\n"
    "7. Change License\n"
    "\n"
    "   As stated in the Notice, on the Change Date (2029-05-07), the Licensed Work\n"
    "   will be made available under the Change License (GPL-3.0). Until that date,\n"
    "   the terms of this License apply.\n"
    "\n"
    "8. Versions of the License\n"
    "\n"
    "   Licensor may publish revised versions of this License. You may use the\n"
    "   Licensed Work under the terms of any version published by Licensor.\n"
    "\n"
    "9. Miscellaneous\n"
    "\n"
    "   This License represents the complete agreement concerning the subject matter\n"
    "   hereof. If any provision of this License is held to be unenforceable, such\n"
    "   provision shall be reformed only to the extent necessary to make it\n"
    "   enforceable.\n"
    )

    print()
    print("  ==============================================")
    print("  Deploy v23b completo!")
    print("  ==============================================")
    print()
    print("  Arquivos atualizados:")
    print("    README.md    - PT-BR com acentuacao + DOIs + criador + BSL 1.1")
    print("    README_EN.md - Ingles completo")
    print("    LICENSE      - Business Source License 1.1")
    print()
    print("  Proximo passo:")
    print("    type README.md")
    print("    type README_EN.md")
    print("    type LICENSE")
    print()

if __name__ == "__main__":
    main()
